#!/usr/bin/env ansible-playbook
---
- hosts: bigbluebutton
  remote_user: root
  gather_facts: yes
  tasks:
  - name: create second record process service
    import_role: { name: multi-record }
    tags: multi-record